### ISSUE TITLE
Plans for complete mp3 decoder?

### ISSUE THREAD

**Issue by cambiata** [djcsdy/mpeg.audio.hx#1]
Hi Daniel! Thanx!

Any plans to extend this component to a complete mp3 decoder?

/ Jonas

**Comment by djcsdy** [comment]
I’m not ruling it out. I don’t currently plan to do that myself, but I have the necessary specs. At the moment for my own purposes i just need to be able to read metadata and gapless playback information.

If someone wants to contribute code or funding then I’m wide open to the idea :).

**Comment by cambiata** [comment]
I would really like to be able to decode mp3s crossplatform, at least flash/cpp/neko. I'm investigating Claus Wahler's As3Icy (https://github.com/claus/as3icy) at the moment - the only as3 decoder I've found. Maybe I'll give it a try... 

Do you know of other decoding libs/solutions that could be subjects for conversion?

**Comment by djcsdy** [comment]
as3icy appears to be a port of JLayer, for Java, so I think I would port code directly from JLayer if I were going to approach it that way. I’ve not looked at either project so I’ve no idea if they make a good match for the code I’ve written so far (although that code is still subject to change for the moment anyway).

It’s not terribly difficult to write a decoder from scratch if you have a copy of the spec, but probably very difficult even to do a port otherwise.

**Comment by cambiata** [comment]
I guess that the essence of Claus's solution, apart from the core decoding stuff (ported from JLayer as you point out), is breaking it down to chunks that can be stepped through by Event.ENTER_FRAME callbacks. 

I tried to remove that, wich locks the UI completely while decoding is running.

While waiting for Worker threading (http://www.bytearray.org/?p=4423), his solution is the only way in pure AS3 to decode and playback the decoded ByteArray at the same time, I guess.

**Comment by djcsdy** [comment]
Yes, you will certainly need to limit the amount of audio data you decode per frame on Flash, if you are doing decoding inside ActionScript.

If you wanted to build something on top of my code, it would make sense to decode MP3 frames on demand, and call MpegAudioReader.readNext() when you need a new MP3 frame to decode (if it returns anything other than a Frame() or End(), just keep calling it again).

However, I’m not really sure why you’d ever want to decode MP3 in realtime in pure Haxe. It would make much more sense to just use Flash’s built-in MP3 decoder. Even if you want to analyse individual samples, or filter the audio in Haxe, you should be able to do that with the Flash audio API (it will introduce significant latency, but so would decoding the audio in Haxe).

In that case this code is still useful if you want to play back MP3s gaplessly in Flash, because it will allow you to read gapless playback information embedded by LAME (and, soon, Fraunhofer) encoders, which you can then use to decide how many samples to skip at the beginning and end of playback. Soon, I hope to provide a simple way to do this and load the MP3 frame data into a `Sound` for playback.

**Comment by cambiata** [comment]
Yep, decoding is really slow. I've been playing a bit more with Claus's library, and refactored it a bit: https://github.com/cambiata/AS3Mp3Decoder, from wich I've learned quit a lot. The processing is done the way you describe, one frame at a time.

If I have time, I will definitely go further in trying to port the code to Haxe. Good exercise, and would be a great tool in the box.
